### ISSUE TITLE
Feature Request -- CONTEXT_MENU(s) @ Word/Kanji Groups View(s)

### ISSUE THREAD

**Issue by am2del** [z1dev/zkanji#17] opened 2018-02-26 14:05 UTC
Of-course, there are currently buttons for this, hence no high priority - rather later on for user convinience:

Would you mind concider the ability to `MENU_CLICK` on a group to get a `CONTEXT_MENU` offering to `DELETE_SELECTED` _(should include a pop-up warning if `SELECTED` has child)_ and on `EMPTY_SPACE` offering to `ADD GROUP` or `GROUP_CONTAINER`.

Currently the `FLOAT` is popping up instead.

**Comment by z1dev** [comment] 2018-02-27 11:26
Thanks for reminding me of this. I meant to do it but I should have written it down somewhere. I'll make a release after some of the positioning bugs were fixed, but this looks simple enough to add right after that.

**Comment by z1dev** [comment] 2018-03-04 13:15
The context-menu in group tree-views is now live. The options should do everything also offered by the buttons. I clicked each option and they worked as intended for me. Can you please verify? If an option breaks, it's possible the corresponding button will behave badly too, because the menu options just do the same thing.

**Comment by am2del** [comment] 2018-03-05 17:13
`Build (UTC): 2018-03-05 @ 16:39`

I can confirm the `CONTEXT_MENU` as well as `BUTTON`(s) fully fuctional.

I'd just like to confirm: Are the `Settings` for the groups covering all groups?
If the answer is **yes**, then all good - go ahead and close the issue.
If the answer is **no**, maybe it should be added to the `CONTEXT_MENU` as well?

Either way, good job.

**Comment by z1dev** [comment] 2018-03-09 09:47
I'm not sure what settings are there for groups that need to be in the context menu. The only separate settings that users should access there is for study, and that is only valid for groups separately.

If you mean the current search settings, it's independent of which group is selected.

**Comment by am2del** [comment] 2018-03-22 18:27
>  If you mean the current search settings, it's independent of which group is selected.

I ment the `SETTINGS`-button @ `Word Group`-view, next to the `PRINT`-button.

Seems it affects all so, just add a link like `Open word group settings` to the `CONTEXT_MENU` making it available there too and declare this done?

**Comment by z1dev** [comment] 2018-03-23 12:05
I see what you mean. I think this must be a misunderstanding. If you check the tooltip for the button next to the `print` button, it'll say `Study with group..." In a way it is a setting window, but it is for starting a study. The options for study can be different for each group, because you might want to study different things with them.

Please confirm that the button is grayed out when multiple groups or no group is selected, and enabled when a single group is selected. This is the intended behavior, and if it does that, I'll close this issue.

**Comment by am2del** [comment] 2018-03-24 08:04
> I see what you mean. I think this must be a misunderstanding.

I can see now it is a misunderstanding, thank you, and the cause of it being the `DIALOG_WINDOW_NAME`:  "Word test settings"
Would it be reasonable change the naming to a closer match to avoid future misunderstandings - e.g. re-name the `DIALOG_WINDOW_NAME` to the likes of "Study settings", "Word study settings" or "Study settings - Word"?

Either way, go ahead and close this issue.

**Comment by z1dev** [comment] 2018-03-24 09:49
Thanks for your input, I'll close the issue. I plan to change most window titles to something like "zkanji - the reason for the window." The actual text might still change, but there can be windows lying around with very unfitting names that will change in the future.

**Closed by z1dev** 2018-03-24 09:49 UTC
