### ISSUE TITLE
Study-mode, Long-term test

### ISSUE THREAD

**Issue by am2del** [z1dev/zkanji#11] opened 2018-01-09 17:39 UTC
Initiated here after being mentioned: [HERE](https://github.com/z1dev/zkanji/issues/8#issuecomment-356096777)
Regarding "study"-mode, invisible/non-existant input for answer - and proposals for potential changes to be concidered.

Just throwing my train of thought out here, some ideas comments may be pointless - others may require a redesign to incorprate properly. _Concider time-effort-result delta_. Raw draft and swift patchwork for some ideas and due to lack of time, didn't double check if any proposal is existant in current version - nor thouroghly checked on anything yet - ...and noted some screenshots got spoiled by WM-effects. Please bear with it.

**NOTE:** Through-out this screenshot-run I didn't enter a single answer at all. If some event was to occour upon this or at "wrong answer", then as you will see - none occoured.

**For ease of reprodocution:**
Starting the test for single kanji (亜), single reading and it's meaning - then screenshots commence right after the "Study now" and selecting "3" at the range.

### Comments on screenshots in sequence order:
_(Screenshots attached in archives below.)_
**--> 01 First box, Query @ ...16-45-00:**  Assuming there should be an input for answer in-between "Enter the answer:"-label and "Show hint..."-button? However, as for "Kanji"-answers - would it be reasonable to use a free-draw box for answer - which gets "disabled"/"non-editable" after hitting "Show answer"-button? Even if not connected to a look-up function, it may be good for practice and to ease up for users to compare their answer with the correct one? Mark "Status" (in this case "New", in colour scale matching various status?)
**--> 01 First box, Answer @ ...16-45-18:** The size of the kanji here, would it be reasonable to match the size with the Kanji Search Widget? Placing the previously mentioned free-draw box disabled at roughly same scale by its side? Plausably with stroke diagrams, or connected to the Kanji Information Dialog for review (automaticly pausing timer)? Mark "Status" (in this case "New", in colour scale matching various status?)
**--> 02 Second box, Query? @ ...16-45-57:** Here's an input box... and "Reveal"-botton. Everything is listed about it... what are these for? If to enter the reading, at least hide the "Kana"-column?
**--> 02 Second box, Answer @ ...16-46-07:** Force "Incorrect" red? Or define a "Wrong/Correct answer"-colours at Settings -> Colour?
**--> 03 Third box, Query @ ...16-46-42:** If this was a "large"-scale test, a single reading in kana is deffinitely insufficient - would suggest to prefer kanji over kana when available as it would be more real-life-like.
**--> 03 Third box, Answer @ ...16-46-50:** See first question comment on "First box, Answer".
**--> 04 Fourth box, Query @ ...16-47-02:** Yet again, no input available. Use a free-draw box like above suggested for Kanji for user to compare side-by-side with answer? Concidering using input-methods - such as i.e. iBus-Anthy or the built-in romaji-to-kana - being a form of cheat.
**--> 04 Fourth box, Answer @ ...16-47-13:** See all comments at "First box, Answer". Just "Kana" instead of "Kanji".

**Screenshots, raw:**
[Screenshot_2018-01-09_Raw.zip](https://github.com/z1dev/zkanji/files/1616053/Screenshot_2018-01-09_Raw.zip)

**Screenshots, with markdown:**
[Screenshot_2018-01-09_MarkDown.zip](https://github.com/z1dev/zkanji/files/1616054/Screenshot_2018-01-09_MarkDown.zip)

**Proposal draft:**
[Proposal_2018-01-09_Draft.zip](https://github.com/z1dev/zkanji/files/1616055/Proposal_2018-01-09_Draft.zip)

_Disclaimer: Please excuse the sloppy patchwork made in a haste. They are named per referense to above comments._

**Comment by z1dev** [comment] 2018-01-10 12:24
Judging only by the screenshots, and if this is what the others see as well, what you see is not a bug. If left at the default settings, there are no input fields at all. It lets the student think of the answer, and when they press the show answer button, they can decide whether they got it right or not, or whether it was too easy. The only thing giving way for misunderstanding is the label "Enter answer" which should say something else in this case.

The long-term study pages in the settings has options to change this behavior. You can check boxes to make input fields appear for the written kanji form, kana form, or definition. But even when entering the answer that way, the student will still have to tell the program whether they had it easy or it was incorrect for example. There are other options there too worth checking out.

As for the request to be able to draw the kanji, this is also possible when you allow input fields to show (by changing the settings.) The usual handwriting tool is shown then, with the candidate list.

I will give a little explanation on how this testing and the one for readings after this is supposed to work:
* In the test, the student has to find one form of the shown word, either the written kanji form (normal way how it would be written in text, I guess,) only kana form, or the definition. This form is marked by a question mark.
* Only one other form of the word is revealed at first. If you need help, or maybe because there are many words with the same kana form, pressing "show hint" will reveal the third form of the word. (The one to answer is still just a question mark.)
* At this point you either (A) use input fields (allowed in the settings,) to enter the answer and press enter when done, or (B) think of the answer, and press show answer when you think you got it.
* The correct answer is revealed. If you used the (A) option, your answer is shown too.
* You can tell the program whether your answer was wrong, whether it was simply fine, or it was easy. The try again option is a bit like saying it's wrong, but with no real consequences at first.

When this is done, the second round of the test is about kanji readings.
* A kanji is shown, and all words that were in the last test that contain this kanji. Only words where the kanji was present with the same reading are shown.
* You have to enter the reading.

This second round doesn't have any consequences. It isn't meant to be a "real" test in the way that you could read the answer right on the screen. It's just a revision for the test, and should be easy. From experience this works really well, since it gives a positive feedback and is more like a game than the test was itself. I used this method in previous versions when studying and it's working for me, so I don't think it needs changes.

Please test the different settings and tell me if there is still a problem (apart from changing the wording of the text for entering the answer.)

**Comment by am2del** [comment] 2018-01-12 19:58
Study-mode so far is about 95% user feedback I've gotten, just brief checks and hasty patch-work. I did take a look at the settings and a few other things and I can see why confusion occoured. Getting back on this later, and a few other things I had on my mind regarding this.
After the 18th or 20th I should be back at normal pace with things, so... gonna check this thoroughly then.

Great description in your last post - any chance you can make something like that go into a "Help/FAQ"-section for study-mode later on?

**Comment by z1dev** [comment] 2018-02-22 12:22
I will close this issue because I'm cleaning up the issues listing. If something specific comes up with study decks please open another.

**Closed by z1dev** 2018-02-22 12:22 UTC
